# Generated by Django 3.1.4 on 2021-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTicketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('no_of_tickets', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Tickets')),
                ('date_of_booking', models.DateTimeField(blank=True, null=True, verbose_name='Booking Date & Time')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
            ],
            options={
                'verbose_name': 'Booked Ticket History',
                'verbose_name_plural': 'Booked Ticket History',
            },
        ),
        migrations.CreateModel(
            name='ReviewSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('user_mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='User Mobile Number')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments/Review')),
                ('date_of_booking', models.DateTimeField(blank=True, null=True, verbose_name='Booking Date & Time')),
                ('is_like', models.BooleanField(default=1, verbose_name='Is Liked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date & Time')),
            ],
            options={
                'verbose_name': 'Review System',
                'verbose_name_plural': 'Review System',
            },
        ),
        migrations.CreateModel(
            name='SeatPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date & Time')),
                ('price_per_seat', models.FloatField(blank=True, max_length=99999.9, null=True, verbose_name='Price')),
                ('total_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Seats')),
                ('active_status', models.BooleanField(default=1, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Seat Pricing',
                'verbose_name_plural': '\t\tSeat Pricing',
            },
        ),
    ]
