# Generated by Django 3.1.4 on 2021-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatpricing',
            name='today_datetime',
            field=models.DateField(blank=True, null=True, verbose_name='Date & Time'),
        ),
    ]
